### ISSUE TITLE
rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R

### ISSUE THREAD

**Issue by seamon** [mana-ethereum/ex_rlp#30]
`moved from ethereumex to here.`

hi there, thanks for your good work.

when i send transaction using `Ethereumex.HttpClient.eth_send_raw_transaction(signed_transaction)`, sometime errors occur just like that:

`no match of right hand side value: {:error, %{"code" => -32000, "message" => "rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R"}}`

ex_rlp version: the latest version `0.5.3`

if i change any part of transaction, `nonce`, `gas_price`, etc., errors disappear.

i searched for a long time, it looks like a problem of RLP, mentioned years before:

[https://ethereum.stackexchange.com/questions/71616/ethereum-boardcast-shows-error-non-canonical-integer-leading-zero-bytes-for](https://ethereum.stackexchange.com/questions/71616/ethereum-boardcast-shows-error-non-canonical-integer-leading-zero-bytes-for)

[https://github.com/MOACChain/moac-core/issues/24](https://github.com/MOACChain/moac-core/issues/24)

it looks like that's hard to reproduce it, cause it's random to generate the leading zeros in R or S. i will try it more using large amount of random transaction arguments, as this error reproduced, it will be posted here.

thanks in advance.

**Comment by seamon** [comment]
well, i reproduced it

```
Enum.map(0..1000, fn n ->
  transaction = %{
    to: "0x0000000000000000000000000000000000000000",
    data: ABI.encode("set(uint)", [1]),
    gas_limit: 100_000,
    gas_price: 1_000_000_000 + n,
    nonce: $YOUR_NONCE_HERE$,
    value: 0
  }

  signature = transaction |> ETH.parse() |> ETH.sign_transaction($YOUR_PRIVATE_KEY_HERE$) |> Base.encode16(case: :lower)
  rs = String.slice(signature, -132..-1)
  <<"a0", r::bytes-size(64), "a0", s::bytes-size(64)>> = rs

  if String.starts_with?(r, "00") do
    IO.puts "n: #{n}"
    IO.puts "r: #{r}\n"
  end
  if String.starts_with?(s, "00") do
    IO.puts "n: #{n}"
    IO.puts "s: #{s}\n"
  end
end)
```

use your own `NONCE` and `PRIVATE_KEY`, run it. generally you will get some lines include value `n` printed:
```
n: 9
s: 006b948db26340a8e953e392b51743499c191edda850f15833e866d59d1282e1
```

use `n` you got, set the transaction, get the signature by using `signature = transaction |> ETH.parse()...`,

then run:
`{:ok, tx_hash} = Ethereumex.HttpClient.eth_send_raw_transaction("0x" <> signature)`,

match error occurs just like this:
`** (MatchError) no match of right hand side value: {:error, %{"code" => -32000, "message" => "rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).S"}}`

hope it helps. thank you.

**Comment by seamon** [comment]
hey guys, i'm back again.

after learning it for hours, it doesn't seem that the leading zero is a RLP problem, and it looks like that's hard to trim the leading zero in function ExRLP.encode(value) by seeing if the value is signature `r` `s` or not.

so i created a PR to `eth`: [https://github.com/izelnakri/eth/pull/18](https://github.com/izelnakri/eth/pull/18), trim the leading zero from signature `r` and `s` directly.

how about that, do you think it's a better solution?

**Comment by ayrat555** [comment]
@seamon I'm sorry for the very late reply. as you discovered the issue is not in ex_rlp it seems
