### ISSUE TITLE
RLP Decode is not correct

### ISSUE THREAD

**Issue by leeduckgo** [mana-ethereum/ex_rlp#31]
```
"what the fuck" |> ExRLP.encode(encoding: :hex) 
"8d7768617420746865206675636b"
```

Decode It in Web3.js：
```
 web3.utils.toAscii("0x8d7768617420746865206675636b")
'what the fuck'
```

There is an extra symbol there

**Comment by ayrat555** [comment]
@leeduckgo 

just tried encoding with https://github.com/ethereumjs/rlp :

```js
import * as rlp from 'rlp'

const data = 'what the fuck'
const encoded = rlp.encode(data)
const decoded = rlp.decode(encoded)

console.log(encoded.toString('hex'))
console.log(decoded.toString())
```

output
```
8d7768617420746865206675636b
what the fuck
```

**Comment by leeduckgo** [comment]
G

> @leeduckgo
> 
> just tried encoding with https://github.com/ethereumjs/rlp :
> 
> ```js
> import * as rlp from 'rlp'
> 
> const data = 'what the fuck'
> const encoded = rlp.encode(data)
> const decoded = rlp.decode(encoded)
> 
> console.log(encoded.toString('hex'))
> console.log(decoded.toString())
> ```
> 
> output
> 
> ```
> 8d7768617420746865206675636b
> what the fuck
> ```

Got, Thx
